### ISSUE TITLE
[BUG] Low TPS spam

### ISSUE THREAD

**Issue by PsychoPE** [Olybear9/Mavoric#45] opened 2020-03-21 15:08 UTC
## Description
This bug allows you to spin, and is really annoying. And it occurs when you type "/bug-report-test-command" in game.
When the server TPS drops anything below 20 you just get spammed in chat 
![4571D2EA-7564-4FBC-AEAF-BDEDF7B65F3A](https://user-images.githubusercontent.com/62428627/77229426-c9484300-6b85-11ea-885f-f5a6dfb63baf.png)

**Additional context**

**Comment by Olybear9** [comment] 2020-03-21 19:45
Duplicate of #42

**Closed by Olybear9** 2020-03-21 19:45 UTC
Labels: Bug, Duplicate
